title: Slowlane
subtitle: The internet homestead of William Pickup
baseurl: "/2024-jekyll-blog" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wpickup
github_username: wpickup

# Build settings

plugins:
  #  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - ".#*"
  - "*~"

permalink: pretty
paginate: 10
paginate_path: /blog/:num

author:
  name: William Pickup
  url: williampickup.org
  email: au.slowlane@gmail.com
  github: https://github.com/wpickup
  mastodon: https://theblower.au/@williamp
  linkedin: https://www.linkedin.com/in/williampickup/
